DATASETS_DIRECTORY = 'datasets'
MUFFIN_VS_CHIHUAHUA_DIRECTORY = 'muffin-vs-chihuahua'
KEYSTROKES_DIRECTORY = 'keystrokes'

FILENAME_TRAIN = 'train'
FILENAME_VALIDATION = 'validation'
FILENAME_TEST = 'test'

DATA_FOLDERS = [FILENAME_TRAIN, FILENAME_VALIDATION, FILENAME_TEST]

IMAGE_SIZE = 64
